
"""
Kraftbeat Model Catalog.
Shared definition of available AI models for both UI and CLI.
"""

MODEL_CATALOG = {
    "small": {
        "display_name": "MusicGen Small",
        "family": "MusicGen",
        "id": "facebook/musicgen-small",
        "params": "300M",
        "vram_gb": 4,
        "download_size": "~3.2 GB",
        "quality": "★★☆☆☆",
        "speed": "★★★★★",
        "stereo": False,
        "melody": False,
        "description": "Fastest model, ideal for testing and low-end hardware. Mono output.",
        "allow_patterns": ["*.safetensors", "*.json", "spiece.model", "generation_config.json", "compression_state_dict.bin"],
    },
    "medium": {
        "display_name": "MusicGen Medium",
        "family": "MusicGen",
        "id": "facebook/musicgen-medium",
        "params": "1.5B",
        "vram_gb": 8,
        "download_size": "~11.1 GB",
        "quality": "★★★★☆",
        "speed": "★★★☆☆",
        "stereo": False,
        "melody": False,
        "description": "Recommended for most users. Great balance of quality and speed.",
        "allow_patterns": ["*.safetensors", "*.json", "spiece.model", "generation_config.json", "compression_state_dict.bin"],
    },
    "large": {
        "display_name": "MusicGen Large",
        "family": "MusicGen",
        "id": "facebook/musicgen-large",
        "params": "3.3B",
        "vram_gb": 16,
        "download_size": "~19.1 GB",
        "quality": "★★★★★",
        "speed": "★★☆☆☆",
        "stereo": False,
        "melody": False,
        "description": "Highest quality mono. Requires 16GB+ VRAM GPU.",
        "allow_patterns": ["*.safetensors", "*.json", "spiece.model", "generation_config.json", "compression_state_dict.bin"],
    },
    "melody": {
        "display_name": "MusicGen Melody",
        "family": "MusicGen",
        "id": "facebook/musicgen-melody",
        "params": "1.5B",
        "vram_gb": 8,
        "download_size": "~8.6 GB",
        "quality": "★★★★☆",
        "speed": "★★★☆☆",
        "stereo": False,
        "melody": True,
        "description": "Use your own audio as melody reference. Great for remixes.",
        "allow_patterns": ["*.safetensors", "*.json", "spiece.model", "generation_config.json", "compression_state_dict.bin"],
    },
    "stereo-medium": {
        "display_name": "MusicGen Stereo Medium",
        "family": "MusicGen",
        "id": "facebook/musicgen-stereo-medium",
        "params": "1.5B",
        "vram_gb": 10,
        "download_size": "~7.3 GB",
        "quality": "★★★★☆",
        "speed": "★★★☆☆",
        "stereo": True,
        "melody": False,
        "description": "True stereo output with wider soundstage. Recommended for music.",
        "allow_patterns": ["*.safetensors", "*.json", "spiece.model", "generation_config.json", "compression_state_dict.bin"],
    },
    "stereo-large": {
        "display_name": "MusicGen Stereo Large",
        "family": "MusicGen",
        "id": "facebook/musicgen-stereo-large",
        "params": "3.3B",
        "vram_gb": 18,
        "download_size": "~19.0 GB",
        "quality": "★★★★★",
        "speed": "★★☆☆☆",
        "stereo": True,
        "melody": False,
        "description": "Best quality stereo. Premium results for serious production.",
        "allow_patterns": ["*.safetensors", "*.json", "spiece.model", "generation_config.json", "compression_state_dict.bin"],
    },
    "stereo-melody": {
        "display_name": "MusicGen Stereo Melody Large",
        "family": "MusicGen",
        "id": "facebook/musicgen-stereo-melody-large",
        "params": "3.3B",
        "vram_gb": 18,
        "download_size": "~14.5 GB",
        "quality": "★★★★★",
        "speed": "★★☆☆☆",
        "stereo": True,
        "melody": True,
        "description": "Stereo + Melody. Control stereo generation with a melody input.",
        "allow_patterns": ["*.safetensors", "*.json", "spiece.model", "generation_config.json", "compression_state_dict.bin"],
    },
    "style": {
        "display_name": "MusicGen Style",
        "family": "MusicGen",
        "id": "facebook/musicgen-style",
        "params": "1.5B",
        "vram_gb": 8,
        "download_size": "~10.6 GB",
        "quality": "★★★★★",
        "speed": "★★★☆☆",
        "stereo": False,
        "melody": False,
        "description": "Style Transfer. Generate music based on text AND an audio style reference.",
        "allow_patterns": ["*.safetensors", "*.json", "spiece.model", "generation_config.json", "compression_state_dict.bin"],
    },
    "songstarter": {
        "display_name": "Songstarter (Community)",
        "family": "MusicGen",
        "id": "nateraw/musicgen-songstarter-v0.2",
        "params": "1.5B",
        "vram_gb": 8,
        "download_size": "~9.3 GB",
        "quality": "★★★★★",
        "speed": "★★★☆☆",
        "stereo": True,
        "melody": False,
        "description": "Community fine-tune for generating musical loops. Fast & fun.",
        "allow_patterns": ["*.bin", "*.json", "spiece.model", "README.md", ".gitattributes"],
    },
    "audiogen": {
        "display_name": "AudioGen (Sound Effects)",
        "family": "AudioGen",
        "id": "facebook/audiogen-medium",
        "params": "1.5B",
        "vram_gb": 8,
        "download_size": "~3.7 GB",
        "quality": "★★★★☆",
        "speed": "★★★☆☆",
        "stereo": False,
        "melody": False,
        "description": "Generate sound effects: explosions, rain, footsteps, etc.",
        "allow_patterns": ["*.safetensors", "*.json", "spiece.model", "compression_state_dict.bin"],
    },
    "magnet-small-10s": {
        "display_name": "MAGNeT Small (10sec)",
        "family": "MAGNeT",
        "id": "facebook/magnet-small-10secs",
        "params": "300M",
        "vram_gb": 4,
        "download_size": "~1.0 GB",
        "quality": "★★★☆☆",
        "speed": "★★★★★",
        "stereo": False,
        "melody": False,
        "description": "MAGNeT (Fast). Generates 10s chunks very quickly. Non-autoregressive.",
        "allow_patterns": ["*.safetensors", "*.json", "spiece.model", "compression_state_dict.bin"],
    },
    "magnet-medium-10s": {
        "display_name": "MAGNeT Medium (10sec)",
        "family": "MAGNeT",
        "id": "facebook/magnet-medium-10secs",
        "params": "1.5B",
        "vram_gb": 8,
        "download_size": "~3.7 GB",
        "quality": "★★★★☆",
        "speed": "★★★★☆",
        "stereo": False,
        "melody": False,
        "description": "Higher quality 10s generation. Fast non-autoregressive.",
        "allow_patterns": ["*.safetensors", "*.json", "spiece.model", "compression_state_dict.bin"],
    },
    "magnet-small-30s": {
        "display_name": "MAGNeT Small (30sec)",
        "family": "MAGNeT",
        "id": "facebook/magnet-small-30secs",
        "params": "300M",
        "vram_gb": 4,
        "download_size": "~1.0 GB",
        "quality": "★★★☆☆",
        "speed": "★★★★★",
        "stereo": False,
        "melody": False,
        "description": "MAGNeT (Fast). Generates 30s chunks. Good compromise for speed.",
        "allow_patterns": ["*.safetensors", "*.json", "spiece.model", "compression_state_dict.bin"],
    },
    "magnet-medium-30s": {
        "display_name": "MAGNeT Medium (30sec)",
        "family": "MAGNeT",
        "id": "facebook/magnet-medium-30secs",
        "params": "1.5B",
        "vram_gb": 8,
        "download_size": "~3.7 GB",
        "quality": "★★★★☆",
        "speed": "★★★★☆",
        "stereo": False,
        "melody": False,
        "description": "High quality 30s generation. Best MAGNeT for production.",
        "allow_patterns": ["*.safetensors", "*.json", "spiece.model", "compression_state_dict.bin"],
    },
    "acestep": {
        "display_name": "ACE-Step (Vocals)",
        "family": "ACESTEP",
        "id": "ACE-Step/ACE-Step-v1-3.5B",
        "params": "3.5B",
        "vram_gb": 8,
        "download_size": "~7.7 GB",
        "quality": "★★★★★",
        "speed": "★★☆☆☆",
        "stereo": True,
        "melody": False,
        "description": "State-of-the-art vocal generation model (3.5B). Generates lyrics and melody.",
        "allow_patterns": ["*.safetensors", "*.json", "*.md", ".gitattributes", "tokenizer.json", "tokenizer_config.json"],
    },
    "acestep-1.5": {
        "display_name": "ACE-Step 1.5 (Vocals)",
        "family": "ACESTEP",
        "id": "ACE-Step/Ace-Step1.5",
        "params": "3.5B",
        "vram_gb": 8,
        "download_size": "~7.7 GB",
        "quality": "★★★★★",
        "speed": "★★★★☆",
        "stereo": True,
        "melody": False,
        "description": "1.5 Upgrade: Faster generation, multilingual support, and better quality.",
        "allow_patterns": ["*.safetensors", "*.json", "*.md", ".gitattributes", "tokenizer.json", "tokenizer_config.json"],
    },
    "acestep-1.5-turbo": {
        "display_name": "ACE-Step 1.5 XL Turbo",
        "family": "ACESTEP",
        "id": "ACE-Step/acestep-v15-xl-turbo",
        "params": "3.5B",
        "vram_gb": 8,
        "download_size": "~7.7 GB",
        "quality": "★★★★☆",
        "speed": "★★★★★",
        "stereo": True,
        "melody": False,
        "description": "Lightning fast XL Turbo model. Needs fewer steps for good quality.",
        "allow_patterns": ["*.safetensors", "*.json", "*.md", ".gitattributes", "tokenizer.json", "tokenizer_config.json"],
    },
    "acestep-1.5-sft": {
        "display_name": "ACE-Step 1.5 XL SFT",
        "family": "ACESTEP",
        "id": "ACE-Step/acestep-v15-xl-sft",
        "params": "3.5B",
        "vram_gb": 8,
        "download_size": "~7.7 GB",
        "quality": "★★★★★",
        "speed": "★★★★☆",
        "stereo": True,
        "melody": False,
        "description": "Highest quality Supervised Fine-Tune of the XL 1.5 model.",
        "allow_patterns": ["*.safetensors", "*.json", "*.md", ".gitattributes", "tokenizer.json", "tokenizer_config.json"],
    },
    "diffrhythm": {
        "display_name": "DiffRhythm (Base)",
        "family": "DIFFRHYTHM",
        "id": "ASLP-lab/DiffRhythm-base",
        "params": "~1.2B",
        "vram_gb": 8,
        "download_size": "~2.1 GB",
        "quality": "★★★★☆",
        "speed": "★★★☆☆",
        "stereo": True,
        "melody": False,
        "description": "Latent diffusion model for generating full songs (4m 45s).",
        "allow_patterns": ["*.pt", "*.json", "*.md", "LICENSE"],
    },
    "diffrhythm-full": {
        "display_name": "DiffRhythm (Full)",
        "family": "DIFFRHYTHM",
        "id": "ASLP-lab/DiffRhythm-full",
        "params": "~1.2B",
        "vram_gb": 10,
        "download_size": "~4.2 GB",
        "quality": "★★★★★",
        "speed": "★★★☆☆",
        "stereo": True,
        "melody": False,
        "description": "Full latent diffusion model with highest quality for full songs.",
        "allow_patterns": ["*.pt", "*.json", "*.md", "LICENSE"],
    },
}
